language: cpp


os:
  - osx
  - linux
  - windows



compiler:
  - gcc
  - clang


dist: xenial
osx_image: xcode10.1


branches:
  only:
    - master


before_script:
  - git checkout master
  - git submodule init
  - git submodule foreach git checkout master
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then cmake .. -G'Unix Makefiles'; else cmake ..; fi


script:
  cmake --build . --config Release --parallel

